#!/bin/bash
if [[ -z "$PORT" ]]; then
    echo "You must add \"-e PORT=<some port>\" when running this" >&2
    exit 1
fi

if [[ -z "$HOST" ]]; then
    echo "No HOST provided, assuming boot2docker's IP: 192.168.59.103"
    export HOST="192.168.59.103"
fi

/bin/sed -i "s/XXX_PORT_XXX/$PORT/" /etc/nginx.conf
/bin/sed -i "s/XXX_HOST_XXX/$HOST/" /etc/nginx.conf

echo "Excepting connections at $HOST:$PORT"
nginx
